VIA_ENABLE = yes

VIA_ENABLE = yes
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

LTO_ENABLE = yes
# AVR_USE_MINIMAL_PRINTF = yes
# SPACE_CADET_ENABLE = no
# MUSIC_ENABLE = no
